# csb - development and install
#
# Copies (not symlinks) bin/csb into a bin dir on your PATH: the target may
# itself be under version control, so it must hold real, portable content.
#
# The native csb-config binary is portable content's opposite, so it goes to
# TOOLS_DIR (~/.csb/bin) instead, which csb searches. That keeps a per-platform
# binary out of a version-controlled bin dir, and keeps it outside every sandbox
# write root -- csb-config decides policy and runs unsandboxed.
#
#   make install                      # bin/csb -> ~/bin, csb-config -> ~/.csb/bin
#   make install BIN_DIR=~/.local/bin # ...or elsewhere
#   make install-completion           # zsh/bash completion -> ~/.csb/share
#   make ci                           # every suite below, cheapest first
#   make check                        # shellcheck the shell scripts
#   make test                         # bats suite (dump-only, fast)
#   make test-escape                  # Tier 3: real launches, run OUTSIDE csb
#   make ocaml-build                  # build csb-config + csb-proxy (dune)
#   make ocaml-test                   # the bats config tests against csb-config
#   make test-proxy                   # egress-proxy tests (real proxy + curl)
#   make proxy-run                    # run csb-proxy in the foreground
#
# `make test` is NOT the whole suite: bats does not recurse, so it runs
# test/*.bats only -- test/escape/ and test/proxy/ have their own targets, and
# the config oracle re-runs a subset against csb-config. `make ci` is the one
# that runs all of them.
#
# `check` and the bats targets prefer a tool already on PATH and fall back to
# csb's own devShell (nix develop), so they work with only Nix installed.
# `ocaml-build` and `install-completion` ALWAYS use the devShell's toolchain
# (NIX_RUN): a host dune would link a host cmdliner, and a host cmdliner binary
# would generate scripts for a protocol the flake's csb-config may not speak.

# Empty inside the devShell (nix develop sets IN_NIX_SHELL), so it never nests.
NIX_RUN := $(if $(IN_NIX_SHELL),,nix develop --command)

BIN_DIR   ?= $(HOME)/bin
DEST      := $(BIN_DIR)/csb
# csb's own dir for native helpers; csb looks here (see CSB_TOOLS_DIR in bin/csb).
# Override it and the copy must be on PATH, or named by CSB_CONFIG_BIN, for csb
# to find it -- install warns when neither holds.
TOOLS_DIR ?= $(HOME)/.csb/bin
TOOLS_DEST := $(TOOLS_DIR)/csb-config
# Shell completion scripts, generated by the devShell's cmdliner so they speak
# the same protocol version as the csb-config it builds.
SHARE_DIR ?= $(HOME)/.csb/share
COMPLETIONS := $(SHARE_DIR)/zsh/site-functions/_csb \
               $(SHARE_DIR)/bash-completion/completions/csb \
               $(SHARE_DIR)/powershell/csb_completion.ps1

# Flake ref csb pulls the claude binary from; mirrors bin/csb's CSB_SELF default.
# Override to refresh a different remote: make refresh CSB_SELF=path:/path/to/csb
CSB_SELF ?= git+ssh://git@git.grandrew.com/atongen/csb.git

.DEFAULT_GOAL := help
.PHONY: help install install-completion uninstall ci check test test-escape test-update test-proxy \
        build update refresh ocaml-build ocaml-test proxy-run

# The OCaml config-resolution layer (docs/PLAN-009-proxy.md s9).
OCAML_DIR  := ocaml
CSB_CONFIG := $(OCAML_DIR)/_build/default/bin/csb_config_cli.exe
CSB_PROXY  := $(OCAML_DIR)/_build/default/bin/csb_proxy_cli.exe
# Egress allowlist csb-proxy serves; override to test a different set:
#   make proxy-run PROXY_ALLOW=/tmp/my-hosts
PROXY_ALLOW ?= templates/allowed-hosts.claude
# Decision log csb-proxy also writes (stderr keeps streaming either way). A path
# the SANDBOX can read, so a denied fetch is self-diagnosable rather than an
# opaque transport error -- see docs/PLAN-009-proxy.md s7 item 4.
# TMPDIR may or may not carry a trailing slash; normalize either form.
PROXY_LOG ?= $(patsubst %/,%,$(or $(TMPDIR),/tmp))/csb-proxy.log

help: ## Show this help
	@echo "csb - targets (BIN_DIR holds the script, TOOLS_DIR the csb-config binary):"
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-10s\033[0m %s\n", $$1, $$2}'

install: ocaml-build install-completion ## Copy bin/csb into BIN_DIR and csb-config into TOOLS_DIR
	@mkdir -p "$(BIN_DIR)" "$(TOOLS_DIR)"
	@rm -f "$(DEST)" "$(TOOLS_DEST)"    # clear any pre-existing symlinks
	@cp bin/csb "$(DEST)"
	@chmod +x "$(DEST)"
	@echo "install: copied -> $(DEST)"
	@cp "$(CSB_CONFIG)" "$(TOOLS_DEST)"
	@chmod +x "$(TOOLS_DEST)"
	@echo "install: copied -> $(TOOLS_DEST)"
	@case ":$$PATH:" in \
		*":$(BIN_DIR):"*) ;; \
		*) echo "install: note - $(BIN_DIR) is not on your PATH" >&2 ;; \
	esac
	@# A TOOLS_DIR csb does not search, and that is not on PATH, yields a csb that
	@# dies on every invocation. Say so at install time, not at first use.
	@if [ "$(TOOLS_DIR)" != "$(HOME)/.csb/bin" ]; then \
		case ":$$PATH:" in \
			*":$(TOOLS_DIR):"*) ;; \
			*) echo "install: warning - $(TOOLS_DIR) is neither csb's default nor on your" >&2; \
			   echo "  PATH, so csb will not find csb-config there;" >&2; \
			   echo "  export CSB_CONFIG_BIN=$(TOOLS_DEST)" >&2 ;; \
		esac; \
	fi

install-completion: ## Generate the zsh and bash completion scripts into SHARE_DIR
	@$(NIX_RUN) cmdliner install tool-completion --standalone-completion csb "$(SHARE_DIR)" >/dev/null
	@echo "install: completion -> $(SHARE_DIR); enable it in your shell rc with"
	@echo "  zsh:  fpath=(\"$(SHARE_DIR)/zsh/site-functions\" \$$fpath)   # before compinit"
	@echo "  bash: source \"$(SHARE_DIR)/bash-completion/completions/csb\""

uninstall: ## Remove csb from BIN_DIR, csb-config from TOOLS_DIR, completion from SHARE_DIR
	@rm -f "$(DEST)" "$(TOOLS_DEST)" $(COMPLETIONS)
	@echo "uninstall: removed $(DEST), $(TOOLS_DEST) and the completion scripts"

# Ordered cheapest and most hermetic first, so a typo fails in seconds rather
# than after a nix-heavy Tier 3. One $(MAKE) per line: passing several targets
# to one would let -j reorder them.
#
# It refuses to run inside csb rather than skipping quietly. test-escape skips
# every arm when CSB_SANDBOX is set (a nested launch is impossible), so an
# in-sandbox run would print a wall of `ok ... # skip` and exit 0 -- a green
# that verified none of Tier 3. test-update is deliberately absent: it rewrites
# the goldens, so a CI target running it could only ever pass.
ci: ## Every suite, cheapest first; refuses to run inside csb
	@[ -z "$$CSB_SANDBOX" ] || { \
		echo "ci: inside csb -- Tier 3 would skip silently and report green." >&2; \
		echo "  run this on the host instead." >&2; exit 1; }
	@$(MAKE) check
	@$(MAKE) test
	@$(MAKE) ocaml-test
	@$(MAKE) test-proxy
	@$(MAKE) test-escape
	@echo "ci: all suites green"

SHELLSCRIPTS := bin/csb templates/home/.claude/statusline.sh \
                test/escape/loopback-probe.sh

check: ## Lint the shell scripts with shellcheck
	@if command -v shellcheck >/dev/null 2>&1; then \
		shellcheck $(SHELLSCRIPTS); \
	else \
		nix develop --command shellcheck $(SHELLSCRIPTS); \
	fi
	@echo "check: shellcheck clean"

test: ocaml-build ## Run the bats test suite (test/)
	@if command -v bats >/dev/null 2>&1; then \
		bats test/; \
	else \
		nix develop --command bats test/; \
	fi

test-escape: ## Tier 3: real launches asserting the PLAN-007 escapes stay closed
	@echo "test-escape: real launches (needs nix + network); run OUTSIDE csb"
	@if command -v bats >/dev/null 2>&1; then \
		bats test/escape/; \
	else \
		nix develop --command bats test/escape/; \
	fi

test-update: ## Regenerate the Tier 2 snapshot goldens for THIS platform
	@if command -v bats >/dev/null 2>&1; then \
		SNAPSHOT_UPDATE=1 bats test/; \
	else \
		nix develop --command env SNAPSHOT_UPDATE=1 bats test/; \
	fi
	@echo "test-update: regenerated test/snapshots/$$(uname -s | tr 'A-Z' 'a-z')/ - review the diff"

ocaml-build: ## Build csb-config + csb-proxy (dune, ocaml/)
	@$(NIX_RUN) dune build --root $(OCAML_DIR)
	@echo "ocaml-build: $(CSB_CONFIG)" >&2
	@echo "ocaml-build: $(CSB_PROXY)" >&2

proxy-run: ocaml-build ## Run csb-proxy in the foreground (port on stdout, decisions on stderr)
	@echo "proxy-run: allowlist $(PROXY_ALLOW); the first line below is the port. Ctrl-C to stop." >&2
	@echo "proxy-run: decisions also logged to $(PROXY_LOG)" >&2
	@echo "proxy-run: then, in another terminal:" >&2
	@echo "  export HTTPS_PROXY=http://127.0.0.1:<port> NO_PROXY=localhost,127.0.0.1" >&2
	@echo "  claude --debug        # /status should show the Proxy row" >&2
	@exec $(CSB_PROXY) "$(PROXY_ALLOW)" --log-file "$(PROXY_LOG)"

test-proxy: ocaml-build ## Egress-proxy tests (real proxy + curl; not in `make test`)
	@if command -v bats >/dev/null 2>&1; then \
		bats test/proxy/; \
	else \
		nix develop --command bats test/proxy/; \
	fi

# Every Tier-1 test that reaches csb only through --dump-config. The
# dump-sandbox tag marks the rest: those need the profile generator, which
# lives in bin/csb.
OCAML_ORACLE := --filter-tags '!dump-sandbox,!needs-bin-csb' test/precedence.bats test/lists.bats \
                test/validation.bats test/config.bats test/agents.bats test/aws.bats \
                test/completion.bats

ocaml-test: ocaml-build ## Config-layer oracle: the bats config tests against csb-config
	@if command -v bats >/dev/null 2>&1; then \
		CSB=$(CSB_CONFIG) bats $(OCAML_ORACLE); \
	else \
		nix develop --command env CSB=$(CSB_CONFIG) bats $(OCAML_ORACLE); \
	fi

build: ## Build the csb package from the flake (nix build .#csb)
	@nix build .#csb
	@echo "build: ./result/bin/csb"

update: ## Re-pin claude-code to its latest upstream in flake.lock
	@nix flake update claude-code
	@echo "update: claude-code re-pinned in flake.lock - review & commit it"

refresh: ## Re-fetch CSB_SELF so --latest stops diffing against a stale flake cache
	@nix flake metadata "$(CSB_SELF)" --refresh >/dev/null
	@echo "refresh: re-fetched $(CSB_SELF)"
